FactoryWebApp/Models/ErrorViewModel.cs
using System;

namespace FactoryWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FactoryWebApp/Controllers/FactoryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DataLayer.Models;
using DataLayer.Repository;
using FactoryWebApp.Models;

namespace FactoryWebApp.Controllers
{
    public class FactoryController : Controller
    {
        private readonly IDataRepository _dataRepository;

        public FactoryController(IDataRepository dataRepository)
        {
            _dataRepository = dataRepository;
        }
        
        public async Task<ActionResult> Get(string id)
        {
            var model = await _dataRepository.GetFactories(id);


            return View(model);
        }

        [HttpGet]

        public async Task<ActionResult> Insert(string id)
        {
            City city = await _dataRepository.GetCity(id);

            return View("Insert", new Factory() { City = city.Name});
        }


        [HttpGet]
        public async Task<ActionResult> Update(string id)
        {
            Factory factory = await _dataRepository.GetFactory(id);
            return View("Update", factory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update([Bind(include: "Name,City,CEO,AreaOfExpertise")] Factory factory)
        {
            if (ModelState.IsValid)
            {
                var factoryFromDb = await _dataRepository.GetFactory(factory.Name);
                if (factoryFromDb == null)
                {
                    return new NotFoundResult();
                }
                factory.Id = factoryFromDb.Id;
                await _dataRepository.UpdateFactory(factory);


            }
            return RedirectToAction("Get/" + factory.City);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Insert([Bind(include: "Name,City,CEO,AreaOfExpertise")] Factory factory)
        {
            if (ModelState.IsValid)
            {
                await _dataRepository.CreateFactory(factory);
            }
            return RedirectToAction("Get/" + factory.City);
        }
    }
}

FactoryWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DataLayer.Models;
using DataLayer.Repository;
using FactoryWebApp.Models;

namespace FactoryWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly IDataRepository _dataRepository;

        public HomeController(IDataRepository dataRepository)
        {
            _dataRepository = dataRepository;
        }
        
        public async Task<ActionResult> Index()
        {
            var model = await _dataRepository.GetCities();            
            return View(model);
        }

        [HttpGet]
        public ActionResult Insert()
        {          

            return View("Insert", new City());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Insert([Bind(include: "Name,Population")] City city)
        {
            if (ModelState.IsValid)
            {
                await _dataRepository.CreateCity(city);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> Update(string id)
        {
            City city = await _dataRepository.GetCity(id);
            return View("Update", city);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update([Bind(include: "Name,Population")] City city)
        {
            if (ModelState.IsValid)
            {
                var cityFromDb = await _dataRepository.GetCity(city.Name);
                if (cityFromDb == null)
                {
                    return new NotFoundResult();
                }
                city.Id = cityFromDb.Id;
                await _dataRepository.UpdateCity(city);


            }
            return RedirectToAction("Index");
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


    }
}

FactoryWebApp/Controllers/WorkerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DataLayer.Models;
using DataLayer.Repository;
using FactoryWebApp.Models;

namespace FactoryWebApp.Controllers
{
    public class WorkerController : Controller
    {
        private readonly IDataRepository _dataRepository;

        public WorkerController(IDataRepository dataRepository)
        {
            _dataRepository = dataRepository;
        }

        [HttpGet]
        
        public async Task<ActionResult> Get(string id)
        {
            var model = await _dataRepository.GetWorkers(id);

            return View(model);
        }
        [HttpGet]       
        public async Task<ActionResult> GetWorkerById(string id)
        {
            var worker = await _dataRepository.GetWorker(id);
            if (worker == null)
                return new NotFoundResult();
            return View("GetWorker", worker);

        }
        [HttpGet]
        
        public async  Task<ActionResult> Insert(string id)
        {
            Factory factory = await _dataRepository.GetFactory(id);

            return View("Insert",new Worker() { Factory = factory.Name});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Insert([Bind(include: "WorkerId,Name,Age,Factory,Salary")] Worker worker)
        {
            if (ModelState.IsValid)
            {
                await _dataRepository.CreateWorker(worker);
            }
            return RedirectToAction("Get/" + worker.Factory);
        }

        [HttpGet]
        public async Task<ActionResult> Update(string id)
        {
            Worker worker = await _dataRepository.GetWorker(id);
            return View("Update", worker);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update([Bind(include: "WorkerId,Name,Age,Factory,Salary")] Worker worker)
        {
            if (ModelState.IsValid)
            {
                var workerFromDb = await _dataRepository.GetWorker(worker.WorkerId);
                if(workerFromDb == null)
                {
                    return new NotFoundResult();
                }
                worker.Id = workerFromDb.Id;
                await _dataRepository.UpdateWorker(worker);
               

            }
            return RedirectToAction("Get/" + worker.Factory);
        }

        public async Task<ActionResult> ConfirmDelete(string id)
        {
            var workerFromDb = await _dataRepository.GetWorker(id);
            return View("ConfirmDelete", workerFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id)
        {
            var worker = await _dataRepository.GetWorker(id);
            if(worker == null)
            {
                return new NotFoundResult();
            }

            var result = await _dataRepository.DeteleWorker(worker.WorkerId);

            if (result)
            {
                TempData["Message"] = "Worker deleted successfully";
            }
            else
            {
                TempData["Message"] = "Error while deleting worker";
            }

            return RedirectToAction("Get/" + worker.Factory);
        }



    }
}

FactoryWebApp/Views/Factory/Get.cshtml
@model List<DataLayer.Models.Factory>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@foreach (var factory in Model)
{
    <h1 style="font-weight:bold;">@factory.City</h1>
    break;
}

<h3>Factory list</h3>


<div id="tableDiv">
    <table class="table">

        <thead>
            <tr>
                <th>Name</th>
                <th>Area of Expertise</th>
                <th>CEO</th>

            </tr>

        </thead>


        <tbody>
            @foreach (var factory in Model)
            {
                <tr>
                    <td>@Html.ActionLink(factory.Name, "Get", "Worker", new { id = factory.Name }, null)</td>
                    <td>@factory.AreaOfExpertise</td>
                    <td>@factory.CEO</td>
                    <td>
                    <td>@Html.ActionLink("Update", "Update", new { id = factory.Name })</td>
                    <td>@Html.ActionLink("Add Worker", "Insert", "Worker", new { id = factory.Name })</td>
                </tr>
            }

        </tbody>

    </table>


</div>

FactoryWebApp/Views/Factory/Insert.cshtml
@model DataLayer.Models.Factory

@{
    ViewData["Title"] = "Insert";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Insert</h2>

<h4>Factory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Insert">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" readonly />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CEO" class="control-label"></label>
                <input asp-for="CEO" class="form-control" />
                <span asp-validation-for="CEO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AreaOfExpertise" class="control-label"></label>
                <input asp-for="AreaOfExpertise" class="form-control" />
                <span asp-validation-for="AreaOfExpertise" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

FactoryWebApp/Views/Factory/Update.cshtml
@model DataLayer.Models.Factory

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Update</h2>

<h4>Factory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CEO" class="control-label"></label>
                <input asp-for="CEO" class="form-control" />
                <span asp-validation-for="CEO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AreaOfExpertise" class="control-label"></label>
                <input asp-for="AreaOfExpertise" class="form-control" />
                <span asp-validation-for="AreaOfExpertise" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

FactoryWebApp/Views/Home/Index.cshtml
@model List<DataLayer.Models.City>

@{
    ViewData["Title"] = "Home Page";
}

<h2>City List</h2>
<p>
    <a asp-action="Insert">Add city</a>

</p>


<div id="tableDiv">
    <table class="table">

        <thead>
            <tr>
                <th>Name</th>
                <th>Population</th>

            </tr>

        </thead>


        <tbody>
            @foreach (var city in Model)
            {
            <tr>
                <td>@Html.ActionLink(city.Name, "Get", "Factory", new { id = city.Name }, null)</td>
                <td>@city.Population</td>
                <td>@Html.ActionLink("Update", "Update", "Home", new { id = city.Name })</td>
                <td>@Html.ActionLink("Add Factory", "Insert", "Factory", new { id = city.Name })</td>
            </tr>
            }

        </tbody>

    </table>


</div>

FactoryWebApp/Views/Home/Insert.cshtml
@model DataLayer.Models.City

@{
    ViewData["Title"] = "Insert";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Insert</h2>

<h4>City</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Insert">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Population" class="control-label"></label>
                <input asp-for="Population" class="form-control" />
                <span asp-validation-for="Population" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

FactoryWebApp/Views/Home/Update.cshtml
@model DataLayer.Models.City

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Update</h2>

<h4>City</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" readonly />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Population" class="control-label"></label>
                <input asp-for="Population" class="form-control" />
                <span asp-validation-for="Population" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FactoryWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FactoryWebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index"  class="navbar-brand">FactoryWebApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>                  
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p></p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

FactoryWebApp/Views/Worker/ConfirmDelete.cshtml
@model DataLayer.Models.Worker

@{
    ViewData["Title"] = "ConfirmDelete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ConfirmDelete</h2>

<h3>Are you sure you want to delete this worker?</h3>
<div>
    <h4>Worker</h4>
    <hr />  
   
    
    <form asp-controller="Worker" asp-action="Delete" method="post">
        <input type="hidden" name="Id" value="@Model.WorkerId" />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.WorkerId)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.WorkerId)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Factory)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Factory)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Age)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Age)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Salary)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Salary)
            </dd>
        </dl>

        <button type="submit" class="btn btn-default">Delete</button> |

    </form>
</div>

FactoryWebApp/Views/Worker/Get.cshtml
@model List<DataLayer.Models.Worker>
@{
    ViewData["Title"] = "Get";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@foreach (var worker in Model)
{
    <h1 style="font-weight:bold;">@worker.Factory</h1>
    break;
}

<h3>Worker List</h3>




<div id="tableDiv">
    <table class="table">

        <thead>
            <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Salary</th>

            </tr>

        </thead>


        <tbody>
            @foreach (var worker in Model)
            {
                <tr>
                    <td>@worker.Name</td>
                    <td>@worker.Age</td>
                    <td>@worker.Salary</td>
                    <td>@Html.ActionLink("Update", "Update", new { id = worker.WorkerId })</td>
                    <td>@Html.ActionLink("Delete", "ConfirmDelete", new { id = worker.WorkerId })</td>
                </tr>
            }

        </tbody>

    </table>


</div>

FactoryWebApp/Views/Worker/GetWorker.cshtml
@model DataLayer.Models.Worker

@{
    ViewData["Title"] = "Get Worker";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Get Worker</h2>
<p>
    <a asp-action="Create">Create new Worker</a>
</p>


<div id="tableDiv">
    <table class="table">

        <thead>
            <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Salary</th>

            </tr>

        </thead>


        <tbody>
            
            
                <tr>
                    <td>@Model.Name</td>
                    <td>@Model.Age</td>
                    <td>@Model.Salary</td>
                    <td>@Html.ActionLink("Update", "Update", new { id = Model.WorkerId })</td>
                    <td>@Html.ActionLink("Delete", "Delete", new { id = Model.WorkerId })</td>
                </tr>
            

        </tbody>

    </table>


</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

FactoryWebApp/Views/Worker/Insert.cshtml
@model DataLayer.Models.Worker

@{
    ViewData["Title"] = "Insert";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Insert</h2>

<h4>Add new Worker</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Insert">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="WorkerId" class="control-label"></label>
                <input asp-for="WorkerId" class="form-control" />
                <span asp-validation-for="WorkerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Factory" class="control-label"></label>
                <input asp-for="Factory" class="form-control" readonly/>
                <span asp-validation-for="Factory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FactoryWebApp/Views/Worker/Update.cshtml
@model DataLayer.Models.Worker

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Update</h2>

<h4>Worker</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="WorkerId" class="control-label"></label>
                <input asp-for="WorkerId" class="form-control" readonly />
                <span asp-validation-for="WorkerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Factory" class="control-label"></label>
                <input asp-for="Factory" class="form-control" />
                <span asp-validation-for="Factory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>


@section Scripts{ 
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}